FROM php:8.2-apache
# Instalamos la extensión necesaria para hablar con MySQL
RUN apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install mysqli pdo pdo_mysql